root: true

extends: airbnb

env:
  browser: true

rules:
  max-len:
    - warn
    - code: 88
  jsx-a11y/no-noninteractive-element-interactions: off
  jsx-a11y/no-noninteractive-tabindex: off

overrides:
  - files: ['*.test.js', '*.test.jsx']
    env:
      jest: true
