// Race action types
export const FETCH_RACES = 'FETCH_RACES';
export const FETCH_RACES_SUCCESS = 'FETCH_RACES_SUCCESS';
export const FETCH_RACES_FAILURE = 'FETCH_RACES_FAILURE';
export const FETCH_RACE_ENTRIES = 'FETCH_RACE_ENTRIES';
export const FETCH_RACE_ENTRIES_SUCCESS = 'FETCH_RACE_ENTRIES_SUCCESS';
export const FETCH_RACE_ENTRIES_FAILURE = 'FETCH_RACE_ENTRIES_FAILURE';
