// Race action types
export const FETCH_RACES = 'FETCH_RACES';
export const FETCH_RACES_SUCCESS = 'FETCH_RACES_SUCCESS';
export const FETCH_RACES_FAILURE = 'FETCH_RACES_FAILURE';
export const FETCH_RACE_ENTRIES = 'FETCH_RACE_ENTRIES';
export const FETCH_RACE_ENTRIES_SUCCESS = 'FETCH_RACE_ENTRIES_SUCCESS';
export const FETCH_RACE_ENTRIES_FAILURE = 'FETCH_RACE_ENTRIES_FAILURE';
export const UPDATE_RACE_ENTRIES_FILTER = 'UPDATE_RACE_ENTRIES_FILTER';

// Statistics actions
export const FETCH_ENTRY_STATISTICS = 'FETCH_ENTRY_STATISTICS';
export const FETCH_ENTRY_STATISTICS_SUCCESS = 'FETCH_ENTRY_STATISTICS_SUCCESS';
export const FETCH_ENTRY_STATISTICS_FAILURE = 'FETCH_ENTRY_STATISTICS_FAILURE';
